"""zero migration

Revision ID: 4d7ed54f61c2
Revises: 
Create Date: 2025-05-10 22:44:48.160787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7ed54f61c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seq_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Enum('TIMIT', name='exercisetag')), nullable=False),
    sa.Column('preview_image', sa.String(length=500), nullable=True),
    sa.Column('background_image', sa.String(length=500), nullable=True),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.Enum('ENGLISH', name='exerciselang'), nullable=False),
    sa.CheckConstraint('difficulty >= 0', name='check_difficulty_non_neg'),
    sa.CheckConstraint('seq_number > 0', name='check_seq_number_natural'),
    sa.PrimaryKeyConstraint('id', 'seq_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
